server:
  port: 8488

#数据库配置信息

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.122.49.164:3306/website
    username: root
    password: root

#mybaits信息配置
mybatis:
  mapper-locations: classpath:mapper/*.xml

#配置日志打印级别
logging:
  level:
    root: info